---
  - name: Copy files
    become: true
    copy:
      src: ~/project/artifact.tar.gz
      dest: /home/ubuntu/artifact.tar.gz
  - name: Unarchive
    become: true
    shell : |
        cd /home/ubuntu/
        tar xvzf artifact.tar.gz -C .

  - name: "Installing Node Dependencies"
    shell: |
      cd /home/ubuntu/
      curl -fsSL https://deb.nodesource.com/setup_13.x | sudo -E bash -
      sudo apt install nodejs -y
      npm i     
  - name: "Executing Node app with PM2"
    shell: |
      cd /home/ubuntu/dist/
      curl -fsSL https://raw.githubusercontent.com/Unitech/pm2/master/packager/setup.deb.sh | sudo -E bash -
      pm2 completion install
      pm2 stop default
      pm2 start main.js

    register: execute_node

  - name: print message
    debug:
      msg: "{{ execute_node.stdout_lines }}"

  - name: "Configure pm2 to start as service"
    become: true
    shell: |
      env PATH=$PATH:/usr/local/bin pm2 startup systemd -u ubuntu --hp /home/ubuntu
